// 8 B-rolls Wubo concrets pour amorcer une table vide.
// Click sur le bouton "Charger des exemples" dans Plateau > B-rolls quand zéro entrée.
export const EXEMPLES_BROLLS = [
  {
    description_plan: 'LED qui s\'allume en slow-mo, plongée 30cm, fond noir, 0.3x sur l\'allumage',
    setup_technique: 'Trépied avec bras horizontal, pièce assombrie, Argibi sur tissu noir',
    duree_min_secondes: 4,
    priorite: 'haute',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Mains d\'enfant qui branchent un fil, gros plan, geste précis',
    setup_technique: 'Téléphone mode macro, lumière naturelle latérale',
    duree_min_secondes: 3,
    priorite: 'haute',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Visage d\'enfant qui réagit (surprise) au moment où la LED s\'allume',
    setup_technique: 'Cadrage centré buste, lumière soft frontale, focus visage',
    duree_min_secondes: 5,
    priorite: 'haute',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Pages magazine feuilletées, plongée, mains qui tournent les pages',
    setup_technique: 'Trépied vertical, lumière douce, magazine ouvert sur table claire',
    duree_min_secondes: 4,
    priorite: 'moyenne',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Argibi posé sur table, plan large produit, fond neutre Wubo',
    setup_technique: 'Trépied frontal, lumière soft 3 points, fond uni jaune ou violet',
    duree_min_secondes: 3,
    priorite: 'moyenne',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Avant/après split screen : enfant tablette à gauche → enfant qui construit à droite',
    setup_technique: 'Deux plans tournés au même endroit, même cadrage, même enfant',
    duree_min_secondes: 6,
    priorite: 'haute',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Plan large atelier en classe, plusieurs enfants en action sur leur kit',
    setup_technique: 'Téléphone main libre, plan d\'ensemble, autorisations parentales OK',
    duree_min_secondes: 8,
    priorite: 'moyenne',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
  {
    description_plan: 'Détail composants Argibi, plan macro sur LEDs, PCB, boutons',
    setup_technique: 'Mode macro téléphone, lumière laterale dure pour relief',
    duree_min_secondes: 3,
    priorite: 'basse',
    statut: 'à_tourner',
    url_video: '',
    url_thumbnail: '',
  },
];
